apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # Tell skaffold that there is a collection of configurations for k8s and where to find it
build:
  local:
    push: false # Do not push images up to docker hub when changes are made
  artifacts:
    - image: mathiasbergqvist/client
      context: client # When changes is made to this directory, update this pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # Sync updated js files to the pod and update it directly
            dest: .
    - image: mathiasbergqvist/commenets
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mathiasbergqvist/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mathiasbergqvist/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mathiasbergqvist/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mathiasbergqvist/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
